apiVersion: v1
kind: Service
metadata:
  name: gin-apiserver
  labels:
    app: gin-apiserver
spec:
  selector:
    app: gin-apiserver
  ports:
    - port: 8081
      targetPort: 8081
      protocol: TCP
      name: http
